on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKE_NAME: cfst-3457-dcda1c040b8f89f67c33836ce8-nonprodbucket-lxespreb6cop
    steps:
      - name: Chek Out
        uses: actions/checkout@v4.1.5
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 14
      - name: Build site
        run: |
          npm ci
          npm run build
      - name: Push to S3
        run: aws s3 cp public s3://${{ env.BUCKE_NAME }}/ --recursive
